### ISSUE TITLE
Remove unused anymore envs from application.yml.erb

### ISSUE THREAD

**Issue by ysv** [openware/peatio#1847]
- Capybara

```yml
  # Capybara configuration variables.
  TEST_SERVER_HOST: 127.0.0.1
  TEST_SERVER_PORT: '3000'
  TEST_APP_HOST:    peatio.tech
  TEST_APP_PORT:    '80'
```
