### ISSUE TITLE
Redis configuration on another node

### ISSUE THREAD

**Issue by AKRathore** [openware/peatio#2022]
Hello Everyone,
To reduce server performance issue, i m thinking to migrate Redis and RabbitMQ on different server,
Is it feasible in current structure? Any suggestions?

Thanks in advance..

**Comment by ysv** [comment]
@AKRathore Hello
It should be possible because as you can see we use `REDIS_URL`  for redis
```yml
connect:
  host: <%= ENV.fetch('RABBITMQ_HOST', 'localhost') %>
  port: <%= ENV.fetch('RABBITMQ_PORT', '5672') %>
  username: <%= ENV.fetch('RABBITMQ_USER', 'guest') %>
  password: <%= ENV.fetch('RABBITMQ_PASSWORD', 'guest') %>
``` 
for rabbitmq

So it's possible to host it in another VM

Ping please if you have any kind of issue with this
